name: "It's called internet"
favicon: null
layout_spectrum: 0.7576797970104963
typography_spectrum: 0.22081415145657957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0712297463323921
  lightness: 0.6113269373308867
  saturation: 0.5398647820111364
  rhythmicContrast: 0.9583539557643235
purpose: []
